# Generated by Django 6.0.6 on 2026-07-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='cnic',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='cnic_back',
            field=models.ImageField(blank=True, null=True, upload_to='verification/cnic_back/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='cnic_front',
            field=models.ImageField(blank=True, null=True, upload_to='verification/cnic_front/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='verification/selfie/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
