# Generated by Django 6.0.6 on 2026-08-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workerprofile_cnic_workerprofile_cnic_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
