# Generated by Django 6.0.6 on 2026-08-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_workerprofile_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='is_online',
        ),
    ]
