# Generated by Django 6.0.6 on 2026-08-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
