# Generated by Django 6.0.6 on 2026-08-17 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_workerprofile_cnic'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('document_type', models.CharField(choices=[('cnic', 'Pakistan CNIC'), ('national_id', 'National ID'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('other', 'Other')], default='cnic', max_length=30)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('document_front', models.ImageField(blank=True, null=True, upload_to='verification/documents/front/')),
                ('document_back', models.ImageField(blank=True, null=True, upload_to='verification/documents/back/')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='verification/selfies/')),
                ('ocr_result', models.JSONField(blank=True, null=True)),
                ('ocr_confidence', models.FloatField(default=0)),
                ('face_match_score', models.FloatField(default=0)),
                ('face_match_status', models.CharField(default='not_checked', max_length=30)),
                ('liveness_status', models.CharField(default='not_checked', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_reviews', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='core.workerprofile')),
            ],
        ),
    ]
