# Generated by Django 6.0.6 on 2026-08-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customerlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlocation',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
