# Generated by Django 6.0.6 on 2026-10-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_customerlocation_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerverification',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
